import type { SkillId } from '../types';
import { FINAL_TO_REGULAR, REGULAR_TO_FINAL } from '../data/skills.ts';
import { classifyWord, stripNikud } from './analyze.ts';
// both generated by scripts/validate-content.ts with hspell
import MISSPELLINGS from '../data/generated/misspellings.json' with { type: 'json' };
import LEXICON from '../data/generated/lexicon.json' with { type: 'json' };

const MIS = MISSPELLINGS as Record<string, string>;
const LEX = new Set(LEXICON as string[]);

const PREFIXES = ['וכש', 'וש', 'וה', 'וב', 'ול', 'ומ', 'כש', 'מה', 'שה', 'ו', 'ה', 'ב', 'כ', 'ל', 'מ', 'ש'];

/**
 * Known misspelling → correct word. The list only holds strings that are not Hebrew words at all
 * (checked with hspell), so the offline checker never "corrects" a real word.
 */
function lookup(tok: string): string | null {
  if (LEX.has(tok)) return null;
  const splits = PREFIXES.filter((p) => tok.startsWith(p) && tok.length - p.length >= 2);
  // a known word behind any prefix means the token is fine (ושולחן = ו + שולחן)
  if (splits.some((p) => LEX.has(tok.slice(p.length)))) return null;
  const direct = MIS[tok];
  if (direct) return direct;
  for (const p of splits) {
    const hit = MIS[tok.slice(p.length)];
    if (hit) return p + hit;
  }
  return null;
}

/** A word we know is spelled correctly (with or without a prefix). */
export function isKnownWord(w: string): boolean {
  return LEX.has(w) || PREFIXES.some((p) => w.startsWith(p) && LEX.has(w.slice(p.length)));
}

/** Deterministic final-letter fix: finals only at the end, regular forms never at the end. */
export function fixFinals(w: string): string {
  let out = '';
  for (let i = 0; i < w.length; i++) {
    const ch = w[i];
    const last = i === w.length - 1;
    if (!last && FINAL_TO_REGULAR[ch]) out += FINAL_TO_REGULAR[ch];
    else if (last && REGULAR_TO_FINAL[ch] && w.length > 1) out += REGULAR_TO_FINAL[ch];
    else out += ch;
  }
  return out;
}

export interface CheckedWord {
  typed: string;
  corrected: string;
  skill?: SkillId | 'other';
  pair?: string;
}

export interface CheckResult {
  words: CheckedWord[];
  corrected: string;
  engine: 'offline' | 'ai';
  feedback?: string;
  creativity?: number;
}

export function checkOffline(text: string): CheckResult {
  const words: CheckedWord[] = [];
  const corrected = stripNikud(text).replace(/[א-ת]+/g, (tok) => {
    let fix = fixFinals(tok);
    fix = lookup(fix) ?? fix;
    if (fix !== tok) {
      const issue = classifyWord(fix, tok)[0];
      words.push({ typed: tok, corrected: fix, skill: issue?.skill, pair: issue?.pair });
    } else words.push({ typed: tok, corrected: tok });
    return fix;
  });
  return { words, corrected, engine: 'offline' };
}
