# (id, display name, channelId, note)
HE = [
 ('ten-min-recipes','מתכונים ב-10 דקות','UCOU3SslVbk3EL1XdR72KiKg',''),
 ('lihi-kroitz','בקלי קלות - ליהי קרויץ','UCYRjRbFiLOyKr89dryIDobw',''),
 ('elia-pastry','הקונדיטורית אליה','UCz-QgIrEOueT-MXbsrDIQ6g','קונדיטורית'),
 ('israel-yosef','מתכונים בקלי קלות - ישראל יוסף','UCAp77G4PqOXvYDTYUXTjWLA',''),
 ('revital-federbush','רויטל פדרבוש - מטבח קל','UCjyKYXVrUwSk4ObrIapxtOA',''),
 ('matkonit','מתכונית','UCf05oCFheATV07EAetRBmuQ',''),
 ('tomer-tomas','תומר תומס','UC3dszMQN0EMI54j58rA4YMA',''),
 ('esty-bar','אסתי בר','UCxnLAYVu0XzrjHhEUbdbOtA',''),
 ('coral-hota','קורל חוטה','UC3e3v-BQixdL5j-kmLNR9Vg','עוגות גבינה'),
 ('shiran-matetyahu','שירן מתתיהו','UCRgcsgzlb2j8a1LefW7TRsQ','אפייה'),
 ('foody','פודי - Foody','UCy_lqFqTpf7HTiv3nNT2SxQ',''),
 ('noam-zigdon','נועם זיגדון','UCigf3LCe_lKjZEcpEsfapdg',''),
 ('bigden','BigDen','UCLmJy4v0T9qNX2W7Gw5sTUg','מטבח יפני'),
 ('toni-mashiah','טוני משיח - מפלצת העוגיות','UC-Ace2cJTSi5wiUOZcaWchw',''),
 ('osem','אסם בישולים','UCDLnFrUET5bJ3X0Bl5-HvZg',''),
 ('chef-refael','כפיר רפאל - שף רפאל','UCQEHcOvjiaptd3m2NOrK9zw',''),
 ('avi-levy','אבי לוי שף','UCN5V7L-kyYI79Vjqy14Jlug',''),
 ('angry-chef','השף העצבני','UCoIvCSseQaMLeLwr9oMzEiw','ניר'),
 ('igor-vainberg','שף איגור ואינברג','UC2ZjGYvmLsWuSJqFkGp_e4g',''),
 ('david-guedj','דוד גדג׳ שף','UCBUnDd41rlJv4SWppKKQMTg',''),
 ('eli-elimelech','שף אלי אלימלך','UCwwLhfUiDvAvt-QYIP9MvlQ',''),
 ('neta-chocolate','נטע בשביל השוקולד','UCZiLY1LNETx52d9Nn7-qXGA','שוקולטיירית'),
 ('guy-peretz','השף גיא פרץ','UCS-zSYCaSZjaYBLwHiYZiuw',''),
 ('itay-aricha','איתי אריכא','UCjFeoSNDIZc91YL0fTLRVng',''),
 ('adi-marom','עדי מרום','UChyDxdAA2AiIwJfMTCqMY7Q','עוגות מעוצבות'),
 ('vardit-haviv','ורדית חביב','UC0CXSMXspDmGrtJ876QU6QA','ערוץ התבשילים הטובים'),
 ('foodik','שחר חן - פודיק','UCboRgkGd3lVVfH4TEy0S9Ug',''),
 ('ron-yohananov','רון יוחננוב','UCh86xe8TEPv5BjZ5npMbP7A','מבשלים ואופים'),
 ('dalia-levy','דליה לוי - תבשילים עיראקים','UCZpLjd1nUa5XJJGNqwu4gPg',''),
 ('smadar-yifrah','סמדר יפרח','UCBwtdR_PRik0SeWU-r_NW7Q','מהמטבח שלי באהבה'),
 ('master-recipes','מאסטר מתכונים','UCdgt8cA4vth_zuOpyE5raDw',''),
 ('matanot-ktanot','מתנות קטנות','UCezk9A7g6el-t4gP582xWgw','בלוג אוכל ואפייה'),
 ('orit-levi','אורית לוי - הפשטות שבאוכל','UCiIG6BGw9EiB6YFk5ANfoTw',''),
 ('foodisgood','FoodisGood','UC04cY8-r3AsGz0F-r-3CznA',''),
 ('rona-shimon','רונה שמעון','UC7xywmWSXNkrUy6H9insxzA',''),
 ('nelly-yampolski','נלי ימפולסקי','UC_FT2QK2J7YRGzOZIvRKgnA','מחמצת'),
 ('hagit-elkabetz','חגית אלקבץ','UCu56v8x0NeSzQlzlj8xOdgA',''),
 ('shifra-nahum','תבשילים וחלומות','UCYD_r_91Bo1DKSsDBYOO5xg',''),
 ('magical-kitchen','המטבח הקסום','UCTB4VSHaYdjQB-1Qtupun-w',''),
 ('ortal-katz','אורטל כץ - פשוט לבשל בבית','UCuix92R7PWg4Rsf78zavd1Q',''),
 ('kal-lehachana','קל להכנה','UC-n8XjOhO3b5m1JDrGw-HZA',''),
 ('carnivores','קרניבורים','UCaRVhkzPRbZ4ldszesSYP-w','בשרים'),
 ('smadi-bomba','סמדי בומבה','UCaxlbfuK5LN43g3ucq7-8mA',''),
 ('sara-ben-nisan','לבשל עם שרה','UCb1kyb-5hXmc2cBN51ShltA',''),
 ('yiska-aton','יסכה עטון','UCmXxvlbcwvy3aVz8d-oRsNQ',''),
 ('shimrit-bake','שמרית - הבית של האפייה','UCYps56t_TJnCl719miat5iw',''),
 ('yehudit-aviv','יהודית אביב - הלוחשת לאוכל','UCEI8DrRd_CXAQ99rt_o1wIA',''),
 ('keto-il','KetoIL - מתכונים קטוגניים','UC_vTBvpeVPE3JevlpOZB_Yw',''),
 ('druze-kitchen','סודות המטבח הדרוזי','UCIW-4yn4o8M92sZCm5YFBHw',''),
 ('roshel-patisserie','רושל פטיסייר','UCHbsb5P1g9z5lOLHqFMdykw',''),
 ('keren-agam','קרן אגם','UCAaGhvq9H0eHztFAGvpkNhQ','קליעת חלות'),
 ('shlomi-cohen','שלומי כהן - בית ספר לאפייה','UCCBv-WrJJB3HAg2nIC54vkw',''),
 ('mayas-cakes','העוגות של מאיה','UC5qiO0JTIfsnXfKB4pCRoRw',''),
 ('estella','אסטלה - כיתת אומן לקונדיטוריה','UC-Fq_EedNv0pwavy8QZ8t9w',''),
 ('chinese-dan','אוכל סיני עם דן','UCy9pmkFc8P1H3w13S_l0oTQ',''),
 ('meir-maman','מאיר ממן מבשל','UCbkHIHGKq-SLgX-bYms3g2Q',''),
 ('itayush-cakes','איתיו׳ש קייקס','UCzO_udtRVUcZgOVTkZk14Qw',''),
 ('daniel-rigbi','דניאל רגבי','UCQEnRH4kwpYul3Y8SUVdx9w',''),
 ('master-chef-il','מאסטר-שף','UCefLax7FnZ3qVG0HrLKd20w',''),
]
